# Prefix players with nick names should have
nickPrefix: "."
# How much money each player should start with
startingMoney: 0
# Interval between player inventory scans for illegal items (in ticks)
scanTicks: 10
# How much it costs for players to commit suicide
suicideCost: 0
# How much it costs for players to tpa
tpaCost: 2
# How much it costs for players to dupe
dupeCost: 2
# How much it costs for players to change their personal time
playerTimeCost: 0
# How much it costs for players to change their personal wheather
playerWeatherCost: 0
# How much it costs for players to set their hat item
hatCost: 0
# How much it costs for players to change their nick name
nickCost: 0
# Maximum speed players can travel (bps^2)/2
maxSpeed: 140
# Enable personal time (requires server reload)
playertime: true
# Enable personal wheather (requires server reload)
playerweather: true
# Enable hats (requires server reload)
hat: true
# Enable nicknames (requires server reload)
nick: true
# Enable the tpa (requires server reload)
tpa: true
# Enable the dupe (requires server reload)
dupe: true
# Enable currency commands (requires server reload)
currency: true
# Enable the suicide command (requires server reload)
suicide: true
# Enable the anti speed
antiSpeed: true
# Delete illegals, does not affect scanDropped
deleteIllegals: true
# Unstack overstacked items
unstackOverstacked: true
# Enable scanning for illegal items dropped in world
deleteDroppedIllegals: true
# Items players are not allowed to overstack
noStack:
  - SHULKER_BOX
  - TOTEM_OF_UNDYING
# Items players are not allowed to have
illegals:
  - END_PORTAL_FRAME
  - BEDROCK
  - BARRIER
  - STRUCTURE_BLOCK
  - COMMAND_BLOCK
# Items players cannot dupe
noDupe:
  - SKELETON_SKULL
  - CREEPER_HEAD
  - ZOMBIE_HEAD
  - PLAYER_HEAD
  - DRAGON_HEAD
  - DRAGON_EGG